### ISSUE TITLE
https://github.com/linkedin/kafka mutation test fail on the clients module

### ISSUE THREAD

**Issue by johnxu21** [aliparsai/LittleDarwin#15]
!!! CAUTION !!!
Code can be changed accidentally. Create a backup first.

NoneTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/littledarwin", line 8, in <module>
    sys.exit(entryPoint())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/__main__.py", line 12, in entryPoint
    LittleDarwin.main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/LittleDarwin.py", line 99, in main
    buildPhase(options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/LittleDarwin.py", line 282, in buildPhase
    databaseKeys = list(mutationDatabase.keys())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 826, in __iter__
    yield from self._mapping
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize

**Comment by aliparsai** [comment]
Hey John, 

I need a bit more info on this. Particularly: what was the input files, the parameters with which you ran the tool, and the version you used. Since this is an error in shelve which is an external library, it's probably a good idea to create a venv first, install LittleDarwin with pip in it, and then retry to see if the error goes away.

**Comment by johnxu21** [comment]
Hi Ali,

 littledarwin  -m -b  -p clients/src/main/ -t ./ -c ./gradlew,clients:test --timeout=180

I did.. "create a venv first, install LittleDarwin with pip in it" but I get the same issue

**Comment by aliparsai** [comment]
I cannot replicate this. It works fine for me. It's most likely an environment issue. Can you send me the full output of the tool, OS info, Python version info, and the env info?

![image](https://user-images.githubusercontent.com/4070877/156839823-d73fdd8f-b781-4a39-b913-64e1d9b5f10c.png)

**Comment by johnxu21** [comment]
Total mutations found:  6695
--> ArithmeticOperatorReplacementUnary: 197
--> AssignmentOperatorReplacementShortcut: 194
--> LogicalOperatorReplacement: 230
--> ConditionalOperatorReplacement: 947
--> ShiftOperatorReplacement: 117
--> RelationalOperatorReplacement: 3154
--> ArithmeticOperatorReplacementShortcut: 138
--> ArithmeticOperatorReplacementBinary: 1050
--> ConditionalOperatorDeletion: 668


!!! CAUTION !!!
Code can be changed accidentally. Create a backup first.

NoneTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/littledarwin", line 8, in <module>
    sys.exit(entryPoint())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/__main__.py", line 12, in entryPoint
    LittleDarwin.main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/LittleDarwin.py", line 99, in main
    buildPhase(options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/littledarwin/LittleDarwin.py", line 282, in buildPhase
    databaseKeys = list(mutationDatabase.keys())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 826, in __iter__
    yield from self._mapping
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize


Python 3.9.7

PATH=../kafka/clients/johnenv/johnenv/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/../sonar-scanner-4.6.0.2311-macosx/bin:/Library/TeX/texbin
__CFBundleIdentifier=com.jetbrains.intellij.ce
SHELL=/bin/zsh
SECURITYSESSIONID=186a4
TERM=xterm-256color
USER=businge
TMPDIR=/var/folders/p1/_8mtjtw130j6g5pw00svpn9r0000gn/T/
LaunchInstanceID=4BFB2FA8-DB7D-421E-9DB1-F8921651B292
COMMAND_MODE=unix2003
TERMINAL_EMULATOR=JetBrains-JediTerm
LOGIN_SHELL=1
__INTELLIJ_COMMAND_HISTFILE__=../Library/Caches/JetBrains/IdeaIC2021.3/terminal/history/jpacman-history2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ML1nfoUW4z/Listeners
XPC_FLAGS=0x0
TERM_SESSION_ID=92c923cf-4fb1-40bc-bbf7-2acd80a0f11f
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LOGNAME=businge
LC_CTYPE=en_BE.UTF-8
XPC_SERVICE_NAME=0
HOME=/Users/businge
SHLVL=1
PWD=../kafka/clients/johnenv/johnenv
OLDPWD=../kafka/clients/johnenv
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home
PS1=(johnenv) %n@%m %1~ %# 
VIRTUAL_ENV=../kafka/clients/johnenv/johnenv
_=/usr/bin/printenv

**Comment by aliparsai** [comment]
I did some digging, and this seems to be a backend in shelve problem on OS X. Apparently the backend shelve uses on OS X has a bug that's still open: https://bugs.python.org/issue30388

Unfortunately there's nothing I can do on my side. You can try to use Windows or Linux instead and the problem will go away.
