### ISSUE TITLE
Problem in the mutation phase

### ISSUE THREAD

**Issue by adrianopizzini** [aliparsai/LittleDarwin#18]
Hi, I think it's another problem

Project: Cucumber-JVM 7.11.1
Source code: cucumber-jvm-7.11.1\cucumber-core\src\main\java\io\cucumber\core\plugin\Banner.java

(76/182) Source file:  C:\Projects\cucumber-jvm-7.11.1\cucumber-core\src\main\java\io\cucumber\core\plugin\Banner.java
ANTLR runtime and generated code versions disagree: 4.11.1!=4.10.1
ANTLR runtime and generated code versions disagree: 4.11.1!=4.10.1
line 61:51 token recognition error at: ''â”'
line 61:54 token recognition error at: '€'
line 61:55 token recognition error at: '', '
line 78:51 token recognition error at: ''â”'
line 78:54 token recognition error at: '€'
line 78:55 token recognition error at: '', '
--> Mutations found:  3
----> ArithmeticOperatorReplacementBinary : 3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\__main__.py", line 16, in <module>
    sys.exit(entryPoint())
             ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\__main__.py", line 12, in entryPoint
    LittleDarwin.main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\LittleDarwin.py", line 92, in main
    mutationPhase(options, filterType, filterList, higherOrder)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\LittleDarwin.py", line 203, in mutationPhase
    targetList.append(javaIO.generateNewFile(srcFile, mutatedFile, javaMutate.mutantsPerLine,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\JavaIO.py", line 177, in generateNewFile
    densityFileHandle.write(densityReport)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 10599: character maps to <undefined>

**Comment by aliparsai** [comment]
You need to update to the latest release either using 
`pip install littledarwin --upgrade`
or downloading the binary directly from the release page.
